In [2]:
import numpy as np
import pandas as pd

from sklearn.decomposition import PCA

In [3]:
X_df = pd.read_csv('objects.csv', index_col='Sample')
X_df.head(10)

Size  Weight  Intensity  Value
Sample                                
1         25      20         43     80
2         32      22         82     81
3         10      12         61     79
4         64      49         69     80
5         88      87         73     82
6         12      32         48     78
7         66      45         42     79
8         37      78         27     80
9         54      49         92     81
10        77      67         55     79

In [4]:
n_comp = 4

In [5]:
pca = PCA(n_components=n_comp).fit(X_df)
X_pca = pca.transform(X_df)

In [6]:
pca.explained_variance_

array([1.22433813e+03, 4.50946245e+02, 1.11363136e+02, 6.74705717e-01])

In [7]:
np.round(pca.explained_variance_ratio_, 3)

array([0.685, 0.252, 0.062, 0.   ])

In [8]:
X_pca_df = pd.DataFrame(X_pca, index=X_df.index, columns=[f'PC{i}' for i in range(1, n_comp+1)])
X_pca_df

PC1        PC2        PC3       PC4
Sample                                           
1      -34.583171 -10.349000 -10.059093  1.275593
2      -24.959880  26.149394   2.187027  0.735198
3      -49.647949   5.718359   1.184444 -0.297711
4       15.717839  11.628366  -5.325937 -0.273932
5       59.126650   7.300704   6.332185  0.743237
6      -35.934351 -12.658137   8.061418 -1.271815
7       12.409693 -11.321348 -19.897843 -0.111596
8       11.555242 -42.407898  14.576582  0.528970
9       10.105423  30.621171  10.093890 -0.218364
10      36.210504  -4.681612  -7.152674 -1.109579

In [9]:
loadings = pca.components_
loadings #element (i,j) is the contribution of feature j to PC{i}

array([[ 0.74403784,  0.66328371,  0.07878101,  0.01599915],
       [ 0.208642  , -0.34339877,  0.91534205,  0.02635762],
       [-0.63470886,  0.66447543,  0.3929621 ,  0.03461002],
       [ 0.00456892, -0.02458473, -0.03902905,  0.99892515]])

In [10]:
load_df = pd.DataFrame(loadings, index=[f'PC{i}' for i in range(1, n_comp+1)], columns=X_df.columns)
load_df

Size    Weight  Intensity     Value
PC1  0.744038  0.663284   0.078781  0.015999
PC2  0.208642 -0.343399   0.915342  0.026358
PC3 -0.634709  0.664475   0.392962  0.034610
PC4  0.004569 -0.024585  -0.039029  0.998925