## Jeremy Marcus Tan - Lab 5

In [1]:
import pandas as pd
import numpy as np
import sklearn

## Ordinary Linear Regression

In [2]:
train = pd.read_csv("Regression-Dataset.csv")

In [3]:
train

X1    X2     Y
0   10  21.0  12.5
1   10  20.0  11.0
2   12  18.0  10.0
3   11  22.0  13.0
4   10  11.5   6.0
5   12   7.0  10.0
6   10   9.0   7.5
7   11  10.0   7.0
8   10   2.0   2.0
9   12   3.0   2.0
10  10   3.0   2.5
11  11   4.0   2.5

In [4]:
X_train = train[["X1", "X2"]]
Y_train = train["Y"]

In [5]:
test = pd.DataFrame([[10,19,9.5],[11,8,7],[12,2.5,2]], columns=['X1','X2','Y'])

In [6]:
test

X1    X2    Y
0  10  19.0  9.5
1  11   8.0  7.0
2  12   2.5  2.0

In [7]:
X_test = test[["X1", "X2"]]
Y_test = test["Y"]

In [8]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, Y_train)

In [9]:
# Model Score r^2
reg.score(X_train,Y_train)

0.8490883911317314

In [10]:
reg.coef_

array([0.60500993, 0.50916287])

In [11]:
reg.intercept_

-4.87433628675639

In [12]:
# SSE (Sum of Squared Errors)

Y_pred = reg.predict(X_train)

residuals = Y_train - Y_pred

sse = np.sum(residuals**2)

print(f"Sum of Squared Errors (SSE) in train set: {sse}")

Sum of Squared Errors (SSE) in train set: 28.924725033084805


In [13]:
reg.score(X_test, Y_test)

0.7981767974357739

In [14]:
# SSE (Sum of Squared Errors)

Y_pred = reg.predict(X_test)

residuals = Y_test - Y_pred

sse = np.sum(residuals**2)

print(f"Sum of Squared Errors (SSE) in test set: {sse}")

Sum of Squared Errors (SSE) in test set: 5.886510074789931


## Lasso Regression

In [15]:
from sklearn import linear_model

lasso = linear_model.Lasso().fit(X_train, Y_train)


In [16]:
lasso.score(X_train, Y_train)

0.832245075755942

In [17]:
lasso.coef_


array([0.        , 0.48447575])

Because lasso regression penalizes the absolute value of the coefficients, the first coefficient in the regression equation was set to zero.

In [18]:
lasso.intercept_

1.8979929239824092

In [19]:
# SSE (Sum of Squared Errors)

Y_pred = lasso.predict(X_train)

residuals = Y_train - Y_pred

sse = np.sum(residuals**2)

print(f"Sum of Squared Errors (SSE) in train set: {sse}")

Sum of Squared Errors (SSE) in train set: 32.153027146777774


In [20]:
lasso.score(X_test, Y_test)

0.8181634364830499

In [21]:
# SSE (Sum of Squared Errors)

Y_pred = lasso.predict(X_test)

residuals = Y_test - Y_pred

sse = np.sum(residuals**2)

print(f"Sum of Squared Errors (SSE) in test set: {sse}")

Sum of Squared Errors (SSE) in test set: 5.303566435911046


## Ridge Regression

In [22]:
ridge = linear_model.Ridge().fit(X_train, Y_train)


In [23]:
ridge.score(X_train, Y_train)

0.8488982444568584

In [24]:
ridge.coef_

array([0.53869891, 0.5077387 ])

Because ridge regression penalizes the sum of squared coefficients, both coefficients in the regression equation are nonzero.

In [25]:
ridge.intercept_

-4.146004990396176

In [26]:
# SSE (Sum of Squared Errors)

Y_pred = ridge.predict(X_train)

residuals = Y_train - Y_pred

sse = np.sum(residuals**2)

print(f"Sum of Squared Errors (SSE) in train set: {sse}")

Sum of Squared Errors (SSE) in train set: 28.961169812435482


In [27]:
ridge.score(X_test, Y_test)

0.8015066988120539

In [29]:
# SSE (Sum of Squared Errors)

Y_pred = ridge.predict(X_test)

residuals = Y_test - Y_pred

sse = np.sum(residuals**2)

print(f"Sum of Squared Errors (SSE) in test set: {sse}")

Sum of Squared Errors (SSE) in test set: 5.789387951315094


## Decision Tree Regression

In [30]:
from sklearn.tree import DecisionTreeRegressor
from sklearn import tree

In [31]:
tree_1 = DecisionTreeRegressor(max_depth = 1).fit(X_train, Y_train)

tree_1.score(X_train, Y_train)

0.7567391304347826

In [32]:
tree_1.score(X_test, Y_test)

0.7610714285714286

In [33]:
print(tree.export_text(tree_1))

|--- feature_1 <= 5.50
|   |--- value: [2.25]
|--- feature_1 >  5.50
|   |--- value: [9.62]



In [34]:
tree_2 = DecisionTreeRegressor(max_depth = 2).fit(X_train, Y_train)

In [35]:
tree_2.score(X_train, Y_train)

0.9241304347826087

In [36]:
tree_2.score(X_test, Y_test)

0.8308333333333333

In [37]:
print(tree.export_text(tree_2))

|--- feature_1 <= 5.50
|   |--- feature_1 <= 3.50
|   |   |--- value: [2.17]
|   |--- feature_1 >  3.50
|   |   |--- value: [2.50]
|--- feature_1 >  5.50
|   |--- feature_1 <= 14.75
|   |   |--- value: [7.62]
|   |--- feature_1 >  14.75
|   |   |--- value: [11.62]

