In [32]:
import tensorflow as tf
import pandas as pd
import os
import numpy as np
import datetime as dt
from random import seed
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import backend as K
from tensorflow.keras import callbacks
from tensorflow.keras import regularizers
#tf.compat.v1.disable_eager_execution()

In [2]:
seed(36)

In [3]:
BASE_DIR_PATH = '/Users/neilb/Documents/dsci_thesis/Datasets'
DATASET_FILE = os.path.join(BASE_DIR_PATH, 'compiled_data_jer_edit.csv')

In [4]:
df = pd.read_csv(DATASET_FILE)
df.head(10)

Unnamed: 0  index  Rainfall_Aries  Rainfall_Boso  Rainfall_Campana  \
0           0      0               0              1                 1   
1           1    365               0              0                 0   
2           2    730               0              0                 0   
3           3   1095               0              0                 1   
4           4   1460               0              0                 0   
5           5   1825               0              0                 1   
6           6   2190               0              0                 0   
7           7   2555               0              0                 0   
8           8   2920               0              0                 1   
9           9   3285               6              5                20   

   Rainfall_Nangka  Rainfall_Oro  Waterlevel_Sto_Nino  Waterlevel_Montalban  \
0                0             0                12.53                 21.39   
1                1             0                12.53                 21.39   
2                0             0                12.53                 21.39   
3                1             0                12.53                 21.39   
4                0             0                12.53                 21.39   
5                0             0                12.53                 21.39   
6                0             0                12.53                 21.39   
7                0             0                12.53                 21.39   
8                0             0                12.53                 21.39   
9                4            20                12.53                 21.39   

   Discharge_Sto_Nino  Discharge_San_Jose  Cross_Section_Sto_Nino  \
0        22695.465738        25325.458412                  826.98   
1        22695.465738        25325.458412                  826.98   
2        22695.465738        25325.458412                  826.98   
3        22695.465738        25325.458412                  826.98   
4        22695.465738        25325.458412                  826.98   
5        22695.465738        25325.458412                  826.98   
6        22695.465738        25325.458412                  826.98   
7        22695.465738        25325.458412                  826.98   
8        22695.465738        25325.458412                  826.98   
9        22695.465738        25325.458412                  826.98   

   Cross_Section_Montalban  Velocity_Sto_Nino  Velocity_Montalban  \
0                    641.7           27.44379           39.466197   
1                    641.7           27.44379           39.466197   
2                    641.7           27.44379           39.466197   
3                    641.7           27.44379           39.466197   
4                    641.7           27.44379           39.466197   
5                    641.7           27.44379           39.466197   
6                    641.7           27.44379           39.466197   
7                    641.7           27.44379           39.466197   
8                    641.7           27.44379           39.466197   
9                    641.7           27.44379           39.466197   

              datetime        t      x  
0  2017-01-01 00:00:00      0.0  14420  
1  2017-01-01 01:00:00   3600.0  14420  
2  2017-01-01 02:00:00   7200.0  14420  
3  2017-01-01 03:00:00  10800.0  14420  
4  2017-01-01 04:00:00  14400.0  14420  
5  2017-01-01 05:00:00  18000.0  14420  
6  2017-01-01 06:00:00  21600.0  14420  
7  2017-01-01 07:00:00  25200.0  14420  
8  2017-01-01 08:00:00  28800.0  14420  
9  2017-01-01 09:00:00  32400.0  14420

In [5]:
df = df[['x', 't', 'Rainfall_Aries', 'Rainfall_Boso', 'Rainfall_Campana', 'Rainfall_Nangka', 'Rainfall_Oro', 'Velocity_Montalban', 'Waterlevel_Sto_Nino', 'Velocity_Sto_Nino']]
df.head(10)

x        t  Rainfall_Aries  Rainfall_Boso  Rainfall_Campana  \
0  14420      0.0               0              1                 1   
1  14420   3600.0               0              0                 0   
2  14420   7200.0               0              0                 0   
3  14420  10800.0               0              0                 1   
4  14420  14400.0               0              0                 0   
5  14420  18000.0               0              0                 1   
6  14420  21600.0               0              0                 0   
7  14420  25200.0               0              0                 0   
8  14420  28800.0               0              0                 1   
9  14420  32400.0               6              5                20   

   Rainfall_Nangka  Rainfall_Oro  Velocity_Montalban  Waterlevel_Sto_Nino  \
0                0             0           39.466197                12.53   
1                1             0           39.466197                12.53   
2                0             0           39.466197                12.53   
3                1             0           39.466197                12.53   
4                0             0           39.466197                12.53   
5                0             0           39.466197                12.53   
6                0             0           39.466197                12.53   
7                0             0           39.466197                12.53   
8                0             0           39.466197                12.53   
9                4            20           39.466197                12.53   

   Velocity_Sto_Nino  
0           27.44379  
1           27.44379  
2           27.44379  
3           27.44379  
4           27.44379  
5           27.44379  
6           27.44379  
7           27.44379  
8           27.44379  
9           27.44379

In [6]:
df.tail(10)

x           t  Rainfall_Aries  Rainfall_Boso  Rainfall_Campana  \
8750  14420  31500000.0               0              0                 0   
8751  14420  31503600.0               0              0                 0   
8752  14420  31507200.0               0              0                 0   
8753  14420  31510800.0               0              0                 0   
8754  14420  31514400.0               0              0                 0   
8755  14420  31518000.0               0              0                 0   
8756  14420  31521600.0               0              0                 0   
8757  14420  31525200.0               0              0                 0   
8758  14420  31528800.0               0              0                 0   
8759  14420  31532400.0               0              0                 0   

      Rainfall_Nangka  Rainfall_Oro  Velocity_Montalban  Waterlevel_Sto_Nino  \
8750                0             0           11.158017                12.44   
8751                0             0           11.158017                12.44   
8752                0             0           11.158017                12.44   
8753                0             0           11.158017                12.44   
8754                0             0           11.158017                12.44   
8755                0             0           11.158017                12.44   
8756                0             0           11.158017                12.44   
8757                0             0           11.158017                12.44   
8758                0             0           11.158017                12.44   
8759                0             0           11.158017                12.44   

      Velocity_Sto_Nino  
8750          22.892954  
8751          22.892954  
8752          22.892954  
8753          22.892954  
8754          22.892954  
8755          22.892954  
8756          22.892954  
8757          22.892954  
8758          22.892954  
8759          22.892954

In [7]:
df['Manning_Coefficient'] = pd.Series([0.033 for i in range(len(df))])
df['Bed_Slope'] = pd.Series([1/1500 for i in range(len(df))])
df.head()

x        t  Rainfall_Aries  Rainfall_Boso  Rainfall_Campana  \
0  14420      0.0               0              1                 1   
1  14420   3600.0               0              0                 0   
2  14420   7200.0               0              0                 0   
3  14420  10800.0               0              0                 1   
4  14420  14400.0               0              0                 0   

   Rainfall_Nangka  Rainfall_Oro  Velocity_Montalban  Waterlevel_Sto_Nino  \
0                0             0           39.466197                12.53   
1                1             0           39.466197                12.53   
2                0             0           39.466197                12.53   
3                1             0           39.466197                12.53   
4                0             0           39.466197                12.53   

   Velocity_Sto_Nino  Manning_Coefficient  Bed_Slope  
0           27.44379                0.033   0.000667  
1           27.44379                0.033   0.000667  
2           27.44379                0.033   0.000667  
3           27.44379                0.033   0.000667  
4           27.44379                0.033   0.000667

In [7]:
# Splitting for time series: split into 70-20-10
n = len(df)
train_df = df[0:int(n*0.7)]
val_df = df[int(n*0.7):int(n*0.9)]
test_df = df[int(n*0.9):]

In [8]:
X_train = np.array(train_df[['Rainfall_Aries', 'Rainfall_Boso', 'Rainfall_Campana', 'Rainfall_Nangka', 'Rainfall_Oro', 'Velocity_Montalban']].values.tolist())
X_train

array([[0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.94661967e+01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 3.94661967e+01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.94661967e+01],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.61938106e+04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.06267695e+04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        8.00000000e+00, 7.40614597e+03]])

In [9]:
X_val = np.array(val_df[['Rainfall_Aries', 'Rainfall_Boso', 'Rainfall_Campana', 'Rainfall_Nangka', 'Rainfall_Oro', 'Velocity_Montalban']].values.tolist())
X_val

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.16162475e+03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.82047461e+03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.82781126e+03],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 1.11580169e+01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.11580169e+01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.11580169e+01]])

In [10]:
X_test = np.array(test_df[['Rainfall_Aries', 'Rainfall_Boso', 'Rainfall_Campana', 'Rainfall_Nangka', 'Rainfall_Oro', 'Velocity_Montalban']].values.tolist())
X_test

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        11.15801693],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        11.15801693],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        11.15801693],
       ...,
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        11.15801693],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        11.15801693],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        11.15801693]])

In [11]:
y_train = np.array(train_df[['Velocity_Sto_Nino', 'Waterlevel_Sto_Nino']].values.tolist())
y_train

array([[ 27.44379034,  12.53      ],
       [ 27.44379034,  12.53      ],
       [ 27.44379034,  12.53      ],
       ...,
       [242.66792016,  13.61      ],
       [206.44137652,  13.53      ],
       [175.6290322 ,  13.45      ]])

In [12]:
y_val = np.array(val_df[['Velocity_Sto_Nino', 'Waterlevel_Sto_Nino']].values.tolist())
y_val

array([[155.58081879,  13.39      ],
       [135.06830455,  13.32      ],
       [119.6553679 ,  13.26      ],
       ...,
       [ 52.31133909,  12.85      ],
       [ 52.31133909,  12.85      ],
       [ 52.31133909,  12.85      ]])

In [13]:
y_test = np.array(test_df[['Velocity_Sto_Nino', 'Waterlevel_Sto_Nino']].values.tolist())
y_test

array([[52.31133909, 12.85      ],
       [52.31133909, 12.85      ],
       [52.31133909, 12.85      ],
       ...,
       [22.8929542 , 12.44      ],
       [22.8929542 , 12.44      ],
       [22.8929542 , 12.44      ]])

In [14]:
def r_square(y_true, y_pred):
    x = y_true
    y = y_pred
    mx = K.mean(x, axis=0)
    my = K.mean(y, axis=0)
    xm, ym = x - mx, y - my
    r_num = K.square(K.sum(xm * ym))
    x_square_sum = K.sum(xm * xm)
    y_square_sum = K.sum(ym * ym)
    r_den = (x_square_sum * y_square_sum) + K.epsilon()
    
    r = r_num / r_den
    return r

In [15]:
def NSE(y_true, y_pred):

    y_pred = K.flatten(y_pred)
    y_true = K.flatten(y_true)

    
    SS_res =  K.sum(K.square(y_true - y_pred)) 
    SS_tot = K.sum(K.square(y_true - K.mean(y_true))) 
    
    return ( 1 - SS_res/(SS_tot + K.epsilon()) )

In [16]:
#PDE Loss Function
def custom_loss(grads_inputs, fric_coeff=K.constant(0.033), slope=K.constant(1/1500)):
    du_dx, du_dt, dh_dx= grads_inputs[:,0], grads_inputs[:,1], grads_inputs[:,2]
    g = K.constant(9.8)
    
    # Create a loss function that adds the MSE loss to the mean of all squared activations of a specific layer
    def loss(y_true,y_pred):
        loss_saint_venant = du_dt + y_pred[:,0] * du_dx + g*dh_dx + g*slope + g*K.square(fric_coeff) * K.square(y_true[:,0])/(K.pow(y_true[:,1], 4/3) + K.epsilon())
        l = K.mean(K.square(loss_saint_venant))

        return 2*l+ K.sum(K.mean(K.square(y_pred - y_true), axis=0))
   
    # Return a function
    return loss

In [47]:
#the error means that grads_u and/or grads_h are None, instead of lists, so they cant be indexed afaik
#code is mostly just copy paste from Mahesh
#may na output na kanina pero the loss is like in the millions or higher pa

model = models.Sequential()
model.add(layers.Dense(64, activation = 'relu', input_shape = (6,)))
model.add(layers.Dense(64, activation = 'relu'))
model.add(layers.Dense(64, activation = 'relu'))
model.add(layers.Dense(2))

grads_u = K.gradients(model.output[:,0], [K.constant(14420.0), K.constant(1440.0)])[0]
grads_h = K.gradients(model.output[:,1], [K.constant(14420.0), K.constant(1440.0)])[0]


du_dx, du_dt, dh_dx = grads_u[:,0], grads_u[:,1], grads_h[:,0]
calc_grads_inputs = K.stack((du_dx, du_dt, dh_dx), axis=1)

model.compile(optimizer = tf.keras.optimizers.legacy.Adam(), loss = [custom_loss(calc_grads_inputs)], metrics=['mse', NSE, r_square])
early_stopping_monitor = callbacks.EarlyStopping(patience = 2, verbose=False)
history = model.fit(X_train,y_train, epochs=20, batch_size=128, validation_data=(X_val,y_val), callbacks=[early_stopping_monitor])


TypeError: 'NoneType' object is not subscriptable

In [45]:
#the output from tensorflow is
#[<tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
#<tf.Tensor: shape=(), dtype=float32, numpy=1.0>]
#seems like this doesnt output a value here

@tf.function
def example():
  a = tf.constant(1.)
  b = 2 * a
  return tf.gradients(a + b, [a, b], stop_gradients=[a, b])

example()

[<tf.Tensor 'PartitionedCall_19:0' shape=() dtype=float32>,
 <tf.Tensor 'PartitionedCall_19:1' shape=() dtype=float32>]

## MAHESH

In [17]:
#PDE Loss Function
def custom_loss(grads_inputs):
    du_dx, du_dt, dh_dx, fric_coeff, slope = grads_inputs[:,0], grads_inputs[:,1], grads_inputs[:,2], grads_inputs[:,3], grads_inputs[:,4]
    g = K.constant(9.8)
    # Create a loss function that adds the MSE loss to the mean of all squared activations of a specific layer
    def loss(y_true,y_pred):
        loss_saint_venant = du_dt + y_pred[:,0] * du_dx + g*dh_dx + g*slope + g*K.square(fric_coeff) * K.square(y_true[:,0])/(K.pow(y_true[:,1], 4/3) + K.epsilon())
        l = K.mean(K.square(loss_saint_venant))

        return 2*l+ K.sum(K.mean(K.square(y_pred - y_true), axis=0))
   
    # Return a function
    return loss

## OWN

In [23]:
# Automatic Differentiation
def get_derivative(model):
    grads_u = K.gradients(model.output[:,0], model.input)[0]
    grads_h = K.gradients(model.output[:,1], model.input)[0]
    
    du_dx, du_dt, dh_dx = grads_u[:,0],grads_u[:,1],grads_h[:,0]
    
    return K.stack((du_dx, du_dt, dh_dx), axis=1)

In [24]:
def compile_and_fit(model, patience=2):
    calc_grad_inputs = get_derivative(model)
    
    early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=patience, mode='min')

    model.compile(
        loss=[custom_loss(calc_grad_inputs)], 
        optimizer='adam', 
        metrics=[tf.keras.metrics.MeanSquaredError(), NSE, r_square]
    )

    history = model.fit(
        X_train,
        y_train,
        epochs=20,
        batch_size=128,
        validation_data=(X_val,y_val),
        callbacks=[early_stopping]
    )

    return history

In [25]:
# Dense Neural Network
dense_model = tf.keras.Sequential([
    layers.Dense(units=64, activation='relu', input_shape=(8,)),
    layers.Dense(units=64, activation='relu'),
    layers.Dense(units=64, activation='relu'),
    layers.Dense(units=2)
])

# Convolutional Neural Network
#conv_model = tf.keras.Sequential([
#    layers.Conv1D(filters=64, kernel_size=(6,), activation='relu', input_shape=(1,8)),
#    layers.Dense(units=64, activation='relu'),
#    layers.Dense(units=64, activation='relu'),
#    layers.Dense(units=2),
#])

# Recurrent Neural Network
lstm_model = tf.keras.models.Sequential([
    layers.LSTM(64, return_sequences=True, input_shape=(1,8)),
    layers.Dense(units=64, activation='relu'),
    layers.Dense(units=64, activation='relu'),
    layers.Dense(units=2)
])

In [26]:
dense_history = compile_and_fit(dense_model)

Train on 6132 samples, validate on 1752 samples
Epoch 1/20
6132/6132 [==============================] - 0s 79us/sample - loss: nan - mean_squared_error: nan - NSE: nan - r_square: nan - val_loss: nan - val_mean_squared_error: nan - val_NSE: nan - val_r_square: nan
Epoch 2/20
6132/6132 [==============================] - 0s 26us/sample - loss: nan - mean_squared_error: nan - NSE: nan - r_square: nan - val_loss: nan - val_mean_squared_error: nan - val_NSE: nan - val_r_square: nan
