In [1]:
import tensorflow as tf
import pandas as pd
import os
import numpy as np
import datetime as dt
from random import seed
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import backend as K
tf.compat.v1.experimental.output_all_intermediates(True)

In [2]:
tf.random.set_seed(36)

## Dataset

In [3]:
BASE_DIR_PATH = '/Users/neilb/Documents/dsci_thesis/Datasets'
DATASET_FILE = os.path.join(BASE_DIR_PATH, 'compiled_data_2016_2017.csv')

In [4]:
df_2016_2017 = pd.read_csv(DATASET_FILE)
df_2016_2017

Unnamed: 0  index  Rainfall_Aries  Rainfall_Boso  Rainfall_Campana  \
0               0      0               0              1                 2   
1               1      1               0              1                 1   
2               2      2               1              1                 1   
3               3      3               0              0                 0   
4               4      4               1              1                 1   
...           ...    ...             ...            ...               ...   
17515       17515  16059               0              0                 0   
17516       17516  16424               0              0                 0   
17517       17517  16789               0              0                 0   
17518       17518  17154               0              0                 0   
17519       17519  17519               0              0                 0   

       Rainfall_Nangka  Rainfall_Oro  Waterlevel_Sto_Nino  \
0                    0             0                12.18   
1                    1             0                12.19   
2                    0             1                12.19   
3                    1             0                12.20   
4                    0             0                12.20   
...                ...           ...                  ...   
17515                0             0                12.44   
17516                0             0                12.44   
17517                0             0                12.44   
17518                0             0                12.44   
17519                0             0                12.44   

       Waterlevel_Montalban  Discharge_Sto_Nino  Discharge_San_Jose  \
0                     21.03           21.033407           14.842428   
1                     21.03           21.280072           14.842428   
2                     21.03           21.280072           14.842428   
3                     21.03           21.529056           14.842428   
4                     21.03           21.529056           14.842428   
...                     ...                 ...                 ...   
17515                 21.18           28.244204           17.224575   
17516                 21.18           28.244204           17.224575   
17517                 21.18           28.244204           17.224575   
17518                 21.18           28.244204           17.224575   
17519                 21.18           28.244204           17.224575   

       Cross_Section_Sto_Nino  Cross_Section_Montalban  Velocity_Sto_Nino  \
0                      803.88                    630.9           0.026165   
1                      804.54                    630.9           0.026450   
2                      804.54                    630.9           0.026450   
3                      805.20                    630.9           0.026738   
4                      805.20                    630.9           0.026738   
...                       ...                      ...                ...   
17515                  821.04                    635.4           0.034401   
17516                  821.04                    635.4           0.034401   
17517                  821.04                    635.4           0.034401   
17518                  821.04                    635.4           0.034401   
17519                  821.04                    635.4           0.034401   

       Velocity_Montalban             datetime           t      x  
0                0.023526  2016-01-01 00:00:00         0.0  14420  
1                0.023526  2016-01-01 01:00:00      3600.0  14420  
2                0.023526  2016-01-01 02:00:00      7200.0  14420  
3                0.023526  2016-01-01 03:00:00     10800.0  14420  
4                0.023526  2016-01-01 04:00:00     14400.0  14420  
...                   ...                  ...         ...    ...  
17515            0.027108  2017-12-31 19:00:00  63140400.0  14420  
17516            0.027108  

In [5]:
df_2016_2017['friction_coeff'] = [0.033 for i in range(len(df_2016_2017))]
df_2016_2017['slope'] = [1/1500 for i in range(len(df_2016_2017))]

df_2016_2017

Unnamed: 0  index  Rainfall_Aries  Rainfall_Boso  Rainfall_Campana  \
0               0      0               0              1                 2   
1               1      1               0              1                 1   
2               2      2               1              1                 1   
3               3      3               0              0                 0   
4               4      4               1              1                 1   
...           ...    ...             ...            ...               ...   
17515       17515  16059               0              0                 0   
17516       17516  16424               0              0                 0   
17517       17517  16789               0              0                 0   
17518       17518  17154               0              0                 0   
17519       17519  17519               0              0                 0   

       Rainfall_Nangka  Rainfall_Oro  Waterlevel_Sto_Nino  \
0                    0             0                12.18   
1                    1             0                12.19   
2                    0             1                12.19   
3                    1             0                12.20   
4                    0             0                12.20   
...                ...           ...                  ...   
17515                0             0                12.44   
17516                0             0                12.44   
17517                0             0                12.44   
17518                0             0                12.44   
17519                0             0                12.44   

       Waterlevel_Montalban  Discharge_Sto_Nino  Discharge_San_Jose  \
0                     21.03           21.033407           14.842428   
1                     21.03           21.280072           14.842428   
2                     21.03           21.280072           14.842428   
3                     21.03           21.529056           14.842428   
4                     21.03           21.529056           14.842428   
...                     ...                 ...                 ...   
17515                 21.18           28.244204           17.224575   
17516                 21.18           28.244204           17.224575   
17517                 21.18           28.244204           17.224575   
17518                 21.18           28.244204           17.224575   
17519                 21.18           28.244204           17.224575   

       Cross_Section_Sto_Nino  Cross_Section_Montalban  Velocity_Sto_Nino  \
0                      803.88                    630.9           0.026165   
1                      804.54                    630.9           0.026450   
2                      804.54                    630.9           0.026450   
3                      805.20                    630.9           0.026738   
4                      805.20                    630.9           0.026738   
...                       ...                      ...                ...   
17515                  821.04                    635.4           0.034401   
17516                  821.04                    635.4           0.034401   
17517                  821.04                    635.4           0.034401   
17518                  821.04                    635.4           0.034401   
17519                  821.04                    635.4           0.034401   

       Velocity_Montalban             datetime           t      x  \
0                0.023526  2016-01-01 00:00:00         0.0  14420   
1                0.023526  2016-01-01 01:00:00      3600.0  14420   
2                0.023526  2016-01-01 02:00:00      7200.0  14420   
3                0.023526  2016-01-01 03:00:00     10800.0  14420   
4                0.023526  2016-01-01 04:00:00     14400.0  14420   
...                   ...                  ...         ...    ...   
17515            0.027108  2017-12-31 19:00:00  63140400.0  14420   
17516            0.

In [6]:
train_2016_2017 = df_2016_2017[:int(0.50*len(df_2016_2017))]
val_2016_2017 = df_2016_2017[int(0.50*len(df_2016_2017)):int(0.75*len(df_2016_2017))]
test_2016_2017 = df_2016_2017[int(0.75*len(df_2016_2017)):]

In [7]:
# all inputs
X_train_2016_2017 = np.array(train_2016_2017[['Rainfall_Aries', 'Rainfall_Boso', 'Rainfall_Campana', 'Rainfall_Nangka', 'Rainfall_Oro', 'x' ,'t', 'Discharge_Sto_Nino', 'friction_coeff', 'slope']].values.tolist())
X_val_2016_2017 = np.array(val_2016_2017[['Rainfall_Aries', 'Rainfall_Boso', 'Rainfall_Campana', 'Rainfall_Nangka', 'Rainfall_Oro', 'x','t', 'Discharge_Sto_Nino', 'friction_coeff', 'slope']].values.tolist())
X_test_2016_2017 = np.array(test_2016_2017[['Rainfall_Aries', 'Rainfall_Boso', 'Rainfall_Campana', 'Rainfall_Nangka', 'Rainfall_Oro', 'x','t', 'Discharge_Sto_Nino', 'friction_coeff', 'slope']].values.tolist())
Y_train_2016_2017 = np.array(train_2016_2017[['Velocity_Sto_Nino','Waterlevel_Sto_Nino']].values.tolist())
Y_val_2016_2017 = np.array(val_2016_2017[['Velocity_Sto_Nino','Waterlevel_Sto_Nino']].values.tolist())
Y_test_2016_2017 = np.array(test_2016_2017[['Velocity_Sto_Nino','Waterlevel_Sto_Nino']].values.tolist())

In [8]:
X_train_2016_2017.shape

(8760, 10)

## Metrics

In [9]:
def r_square(y_true, y_pred):
    x = y_true
    y = y_pred
    mx = K.mean(x, axis=0)
    my = K.mean(y, axis=0)
    xm, ym = x - mx, y - my
    r_num = K.square(K.sum(xm * ym))
    x_square_sum = K.sum(xm * xm)
    y_square_sum = K.sum(ym * ym)
    r_den = (x_square_sum * y_square_sum) + K.epsilon()
    
    r = r_num / r_den
    return r

In [10]:
def NSE(y_true, y_pred):
    '''
    This is the Nash-Sutcliffe Efficiency Coefficient
    '''
    y_pred = K.flatten(y_pred)
    y_true = K.flatten(y_true)

    
    SS_res =  K.sum(K.square(y_true - y_pred)) 
    SS_tot = K.sum(K.square(y_true - K.mean(y_true))) 
    
    return ( 1 - SS_res/(SS_tot + K.epsilon()) )

## Models and Training Loops

In [11]:
def create_train_dnn_model(X_train, y_train, X_val, y_val, max_epochs=20, patience=2):
    # Create the model
    model = models.Sequential([
        layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        layers.Dense(64, activation='relu'),
        layers.Dense(64, activation='relu'),
        layers.Dense(2, activation='linear')  # 2 outputs: velocity and water level
    ])
    
    # Define early stopping callback
    early_stopping = tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=patience,
        mode='min'
    )
    
    # Compile the model
    model.compile(
        optimizer='adam',
        loss=tf.keras.losses.MeanSquaredError(),
        metrics=[tf.keras.metrics.MeanSquaredError(), NSE, r_square]
    )
    
    # Train the model
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=max_epochs,
        callbacks=[early_stopping]
    )
    
    return model, history

In [12]:
def create_train_cnn_model(X_train, y_train, X_val, y_val, max_epochs=20, patience=2):
    # Reshape input for 1D CNN
    X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
    X_val = X_val.reshape(X_val.shape[0], X_val.shape[1], 1)
    
    conv_model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(X_train.shape[1], 1)),
        tf.keras.layers.Conv1D(filters=64, kernel_size=6, activation='relu'),
        tf.keras.layers.MaxPooling1D(pool_size=2),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dense(units=2)
    ])
    
    early_stopping = tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=patience,
        mode='min'
    )
    
    conv_model.compile(
        optimizer='adam',
        loss=tf.keras.losses.MeanSquaredError(),
        metrics=[tf.keras.metrics.MeanSquaredError(), NSE, r_square]
    )
    
    conv_history = conv_model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=max_epochs,
        callbacks=[early_stopping]
    )
    
    return conv_model, conv_history

In [13]:
def create_train_lstm_model(X_train, y_train, X_val, y_val, max_epochs=20, patience=2):
    if len(X_train.shape) == 2:
        X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
    if len(X_val.shape) == 2:
        X_val = X_val.reshape((X_val.shape[0], 1, X_val.shape[1]))
            
    lstm_model = tf.keras.models.Sequential([
        tf.keras.layers.LSTM(64, input_shape=(X_train.shape[1], X_train.shape[2]), return_sequences=True),
        tf.keras.layers.Flatten(),  # Add Flatten layer to handle dimension mismatch
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dense(units=64, activation='relu'),
        tf.keras.layers.Dense(units=2)
    ])
    
    # Define early stopping callback
    early_stopping = tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=patience,
        mode='min'
    )
    
    # Compile the model
    lstm_model.compile(
        optimizer='adam',
        loss=tf.keras.losses.MeanSquaredError(),
        metrics=[tf.keras.metrics.MeanSquaredError(), NSE, r_square]
    )
    
    # Train the model
    lstm_history = lstm_model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=max_epochs,
        callbacks=[early_stopping]
    )
    
    return lstm_model, lstm_history

## Training

In [14]:
dnn_model, dnn_history = create_train_dnn_model(
    X_train=X_train_2016_2017,
    y_train=Y_train_2016_2017,
    X_val=X_val_2016_2017,
    y_val=Y_val_2016_2017,
    max_epochs=20,
    patience=2
)

Epoch 1/20
274/274 [==============================] - 3s 5ms/step - loss: 8845185024.0000 - mean_squared_error: 8845185024.0000 - NSE: -225301280.0000 - r_square: 0.2178 - val_loss: 1824797.0000 - val_mean_squared_error: 1824797.0000 - val_NSE: -51787.5664 - val_r_square: 0.0413
Epoch 2/20
274/274 [==============================] - 1s 4ms/step - loss: 477088.4688 - mean_squared_error: 477088.4688 - NSE: -12445.5469 - r_square: 0.1711 - val_loss: 2494621.2500 - val_mean_squared_error: 2494621.2500 - val_NSE: -70746.3828 - val_r_square: 0.0386
Epoch 3/20
274/274 [==============================] - 1s 3ms/step - loss: 397406.1250 - mean_squared_error: 397406.1250 - NSE: -10383.0693 - r_square: 0.1766 - val_loss: 914386.0625 - val_mean_squared_error: 914386.0625 - val_NSE: -25973.2598 - val_r_square: 0.0442
Epoch 4/20
274/274 [==============================] - 1s 3ms/step - loss: 347223.9375 - mean_squared_error: 347223.9375 - NSE: -9063.6992 - r_square: 0.1887 - val_loss: 1302215.6250 - va

In [15]:
cnn_model, cnn_history = create_train_cnn_model(
    X_train=X_train_2016_2017,
    y_train=Y_train_2016_2017,
    X_val=X_val_2016_2017,
    y_val=Y_val_2016_2017,
    max_epochs=20,
    patience=2 )

Epoch 1/20
274/274 [==============================] - 2s 4ms/step - loss: 5384750592.0000 - mean_squared_error: 5384750592.0000 - NSE: -137010448.0000 - r_square: 0.1887 - val_loss: 78528.4141 - val_mean_squared_error: 78528.4141 - val_NSE: -2228.5242 - val_r_square: 0.0201
Epoch 2/20
274/274 [==============================] - 1s 4ms/step - loss: 2516240.0000 - mean_squared_error: 2516240.0000 - NSE: -65621.8672 - r_square: 0.1012 - val_loss: 95016.5547 - val_mean_squared_error: 95016.5547 - val_NSE: -2695.1912 - val_r_square: 0.0162
Epoch 3/20
274/274 [==============================] - 1s 4ms/step - loss: 21644.5723 - mean_squared_error: 21644.5723 - NSE: -564.5762 - r_square: 0.0942 - val_loss: 46492.3906 - val_mean_squared_error: 46492.3906 - val_NSE: -1319.9396 - val_r_square: 0.0197
Epoch 4/20
274/274 [==============================] - 1s 4ms/step - loss: 19769.4805 - mean_squared_error: 19769.4805 - NSE: -515.0973 - r_square: 0.1032 - val_loss: 81369.2969 - val_mean_squared_error

In [16]:
# Train the model
lstm_model, lstm_history = create_train_lstm_model(
    X_train=X_train_2016_2017,
    y_train=Y_train_2016_2017,
    X_val=X_val_2016_2017,
    y_val=Y_val_2016_2017,
    max_epochs=20,
    patience=2
)

Epoch 1/20
274/274 [==============================] - 4s 6ms/step - loss: 10.2996 - mean_squared_error: 10.2996 - NSE: 0.7319 - r_square: 0.0016 - val_loss: 0.1403 - val_mean_squared_error: 0.1403 - val_NSE: 0.9960 - val_r_square: 5.5984e-13
Epoch 2/20
274/274 [==============================] - 1s 4ms/step - loss: 0.2356 - mean_squared_error: 0.2356 - NSE: 0.9939 - r_square: 2.9790e-04 - val_loss: 0.0907 - val_mean_squared_error: 0.0907 - val_NSE: 0.9974 - val_r_square: 9.9480e-13
Epoch 3/20
274/274 [==============================] - 1s 5ms/step - loss: 0.2306 - mean_squared_error: 0.2306 - NSE: 0.9940 - r_square: 3.3428e-04 - val_loss: 0.1752 - val_mean_squared_error: 0.1752 - val_NSE: 0.9950 - val_r_square: 6.2257e-14
Epoch 4/20
274/274 [==============================] - 1s 4ms/step - loss: 0.2308 - mean_squared_error: 0.2308 - NSE: 0.9940 - r_square: 3.2968e-04 - val_loss: 0.0747 - val_mean_squared_error: 0.0747 - val_NSE: 0.9979 - val_r_square: 6.2258e-14
Epoch 5/20
274/274 [======

## Predictions

In [17]:
X_test_2016_2017

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.48177362e+01, 3.30000000e-02, 6.66666667e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.44508667e+01, 3.30000000e-02, 6.66666667e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.40913310e+01, 3.30000000e-02, 6.66666667e-04],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.82442037e+01, 3.30000000e-02, 6.66666667e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.82442037e+01, 3.30000000e-02, 6.66666667e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.82442037e+01, 3.30000000e-02, 6.66666667e-04]])

In [19]:
X_test_2016_2017.shape

(4380, 10)

In [18]:
X_test_2016_2017_lstm = X_test_2016_2017.reshape((X_test_2016_2017.shape[0], 1, X_test_2016_2017.shape[1]))

X_test_2016_2017_lstm

array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.48177362e+01, 3.30000000e-02, 6.66666667e-04]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.44508667e+01, 3.30000000e-02, 6.66666667e-04]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.40913310e+01, 3.30000000e-02, 6.66666667e-04]],

       ...,

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         2.82442037e+01, 3.30000000e-02, 6.66666667e-04]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         2.82442037e+01, 3.30000000e-02, 6.66666667e-04]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         2.82442037e+01, 3.30000000e-02, 6.66666667e-04]]])

In [20]:
# (batch size, time steps, features)
X_test_2016_2017_lstm.shape

(4380, 1, 10)

In [22]:
# LSTM predictions

lstm_predictions_without_window_all_variables = lstm_model(X_test_2016_2017_lstm) 

In [23]:
lstm_predictions_without_window_all_variables

<tf.Tensor: shape=(4380, 2), dtype=float32, numpy=
array([[ 0.01346623, 12.292316  ],
       [ 0.01346623, 12.292316  ],
       [ 0.01346623, 12.292316  ],
       ...,
       [ 0.01346623, 12.292316  ],
       [ 0.01346623, 12.292316  ],
       [ 0.01346623, 12.292316  ]], dtype=float32)>

In [24]:
y_pred_h = lstm_predictions_without_window_all_variables[:,1]
y_pred_v = lstm_predictions_without_window_all_variables[:,0]

In [25]:
y_pred_h

<tf.Tensor: shape=(4380,), dtype=float32, numpy=
array([12.292316, 12.292316, 12.292316, ..., 12.292316, 12.292316,
       12.292316], dtype=float32)>

In [26]:
y_pred_v

<tf.Tensor: shape=(4380,), dtype=float32, numpy=
array([0.01346623, 0.01346623, 0.01346623, ..., 0.01346623, 0.01346623,
       0.01346623], dtype=float32)>

In [27]:
Y_test_2016_2017

array([[ 0.01888235, 11.89      ],
       [ 0.01844587, 11.87      ],
       [ 0.0180173 , 11.85      ],
       ...,
       [ 0.03440052, 12.44      ],
       [ 0.03440052, 12.44      ],
       [ 0.03440052, 12.44      ]])

In [28]:
y_true_h = Y_test_2016_2017[:,1]
y_true_v = Y_test_2016_2017[:,0]

In [29]:
y_true_h

array([11.89, 11.87, 11.85, ..., 12.44, 12.44, 12.44])

In [30]:
y_true_v

array([0.01888235, 0.01844587, 0.0180173 , ..., 0.03440052, 0.03440052,
       0.03440052])

In [31]:
n = len(Y_test_2016_2017)
mse_h = np.mean(np.square(y_true_h - y_pred_h))
mse_v = np.mean(np.square(y_true_v - y_pred_v))

mse_h, mse_v

(0.42879322, 0.0028713248)

In [33]:
(mse_h + mse_v)/2

0.21583227813243866

In [34]:
SS_res_h = np.sum(np.square(y_true_h - y_pred_h)) 
SS_tot_h = np.sum(np.square(y_true_h - np.mean(y_true_h)))

NSE_h = 1 - SS_res_h/(SS_tot_h)
NSE_h

-0.38106958070518515

In [35]:
SS_res_v = np.sum(np.square(y_true_v - y_pred_v)) 
SS_tot_v = np.sum(np.square(y_true_v - np.mean(y_true_v)))

NSE_v = 1 - SS_res_v/(SS_tot_v)
NSE_v

-0.7006108458891884