# Algorithms for Linear Systems and Matrix Factorizations

In [2]:
# Needed Modules/Packages

import numpy as np

## Back Substitution

In [2]:
# Back Substitution

def backSubstitution(U, b):
    """
    U = n x n upper triangular matrix with non-zero diagonal entries
    b = n x 1 vector
    """
    n = len(b)
    x = np.zeros(n)
    x[n - 1] = b[n - 1]/U[n - 1, n - 1]

    for i in range(n - 2, -1, -1):
        SUM = sum([U[i, j]*x[j] for j in range(i, n)])
        x[i] = (b[i] - SUM)/U[i, i]
    
    return x

# Test Data

U = np.array([[1, 2, 3, 1], [0, 2, 4, 2], [0, 0, 3, 1], [0, 0, 0, 1]])
b = np.array(range(4))

print("U = \n\n", U, "\n\n b =",  b, "\n\n x =", backSubstitution(U, b))

U = 

 [[1 2 3 1]
 [0 2 4 2]
 [0 0 3 1]
 [0 0 0 1]] 

 b = [0 1 2 3] 

 x = [ 1.66666667 -1.83333333 -0.33333333  3.        ]


## Forward Substitution

In [3]:
# Forward Substitution

def forwardSubstitution(L, b):
    """
    L = n x n lower triangular matrix with non-zero diagonal entries
    b = n x 1 vector
    """
    n = len(b)
    x = np.zeros(n)
    x[0] = b[0]/L[0, 0]

    for i in range(1, n, 1):
        SUM = sum([L[i, j]*x[j] for j in range(0, i)])
        x[i] = (b[i] - SUM)/L[i, i]
    return x

# Test Data

L = np.array([[1, 0, 0, 0], [1, 2, 0, 0], [3, 4, 5, 0], [2, 1, 2, 1]])
b = np.array([1, 2, 3, 4])

print("L = \n\n", L, "\n\n c =",  b, "\n\n x =", forwardSubstitution(L, b))

L = 

 [[1 0 0 0]
 [1 2 0 0]
 [3 4 5 0]
 [2 1 2 1]] 

 c = [1 2 3 4] 

 x = [ 1.   0.5 -0.4  2.3]


## Row Echelon Form without Type 1 Operation

In [4]:
# Row Echelon Form without Type 1 Operation

def rowEchelonForm_NoType1(M):
    """
    M = m x n matrix with non-zero pivots
    """
    m, n = np.shape(M)
    minmn = min(m, n)
    M = M.copy() # To avoid changing the original matrix
    
    for i in range(minmn):
        for j in range(i + 1, m):
            M[j] = (-M[j, i]/M[i, i])*M[i] + M[j]
    
    return M

# Test Data

# Dealing with Integers
M = np.array([[1, 0, 3], [4, 5, 6], [7, 8, 9]])
print("\n\n M = \n\n", M, "\n\n Mref = \n\n", rowEchelonForm_NoType1(M))

# Dealing with Decimals
M = np.array([[1.0, 0, 3], [4, 5, 6], [7, 8, 9]])
print("\n\n M = \n\n", M, "\n\n Mref = \n\n", rowEchelonForm_NoType1(M))

# Dealing with Decimals (Alternative)
M = np.array([[1, 0, 3], [4, 5, 6], [7, 8, 9]], dtype = 'float64')
print("\n\n M = \n\n", M, "\n\n Mref = \n\n", rowEchelonForm_NoType1(M))




 M = 

 [[1 0 3]
 [4 5 6]
 [7 8 9]] 

 Mref = 

 [[ 1  0  3]
 [ 0  5 -6]
 [ 0  0 -2]]


 M = 

 [[1. 0. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

 Mref = 

 [[ 1.   0.   3. ]
 [ 0.   5.  -6. ]
 [ 0.   0.  -2.4]]


 M = 

 [[1. 0. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

 Mref = 

 [[ 1.   0.   3. ]
 [ 0.   5.  -6. ]
 [ 0.   0.  -2.4]]


 M = 

 [[0. 2. 1.]
 [2. 6. 1.]
 [1. 1. 4.]] 

 Mref = 

 [[  0.   2.   1.]
 [ nan -inf -inf]
 [ nan  nan  nan]]


C:\Users\jerem\AppData\Local\Temp\ipykernel_9828\2568685686.py:13: RuntimeWarning: divide by zero encountered in scalar divide
  M[j] = (-M[j, i]/M[i, i])*M[i] + M[j]
C:\Users\jerem\AppData\Local\Temp\ipykernel_9828\2568685686.py:13: RuntimeWarning: invalid value encountered in multiply
  M[j] = (-M[j, i]/M[i, i])*M[i] + M[j]
C:\Users\jerem\AppData\Local\Temp\ipykernel_9828\2568685686.py:13: RuntimeWarning: invalid value encountered in scalar divide
  M[j] = (-M[j, i]/M[i, i])*M[i] + M[j]


## LU Factorization

In [5]:
# LU-Factorization

def LUFactorization(M):
    """
    M = n x n matrix with non-zero diagonal entries
    """
    n = np.shape(M)[0]
    U = M.copy() # To avoid changing the original matrix
    I = np.identity(n)
    L = np.identity(n)
    
    for i in range(n - 1):
        for j in range(i + 1, n):
            E = np.identity(n)
            E[j] = (U[j, i]/U[i, i])*I[i] + I[j] # Elementary matrix inverse of the previous operation  
            L = L@E
            U[j] = (-U[j, i]/U[i, i])*U[i] + U[j]
    
    return [L, U]

# Test Data

M = np.array([[1.0, 0, 3], [4, 5, 6], [7, 8, 9]])
L, U = LUFactorization(M)
print("M =", M, "\n\n L =", L, "\n\n U =", U) 
print("\n M =?= LU: ", np.array_equal(M, L@U))

M = [[1. 0. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

 L = [[1.  0.  0. ]
 [4.  1.  0. ]
 [7.  1.6 1. ]] 

 U = [[ 1.   0.   3. ]
 [ 0.   5.  -6. ]
 [ 0.   0.  -2.4]]

 M =?= LU:  True


In [ ]:
# Permuted LU Factorization

def permutedLUFactorization(M):
    """
    M = n x n matrix non-singular matrix
    """
    n = np.shape(M)[0]
    I = np.identity(n)
    P = np.identity(n)
    U = M.copy() # To avoid changing the original matrix
    L = np.identity(n)

    for i in range(n - 1):
        if U[i, i] == 0:
            for j in range(i + 1, n):
                if U[j, i] != 0:
                    Pci = np.copy(P[i])
                    Pcj = np.copy(P[j])
                    P[i] = Pcj
                    P[j] = Pci
                    Uci = np.copy(U[i])
                    Ucj = np.copy(U[j])
                    U[i] = Ucj                   
                    U[j] = Uci
                    Lci = np.copy(L[i])
                    Lcj = np.copy(L[j])
                    for k in range(i): 
                        #interchange values before the ith column as well
                        L[i, k] = Lcj[k]
                        L[j, k] = Lci[k]
                    break
        for j in range(i + 1, n):
            cij = U[j, i]/U[i, i]
            U[j] = -cij*U[i] + U[j]
            L[j, i] = cij      
    
    return [P, L, U]

# Test Data

M = np.array([[1, 2, -1, 0], [2, 4, -2, -1], [-3, -5, 6, 1], [-1, 2, 8, -2]], dtype=float)    
P, L, U = permutedLUFactorization(M)

print("\n M = \n\n", M, "\n\n P = \n\n", P, "\n\n L = \n\n", L, "\n\n U = \n\n", U)
print("\n PM =?= LU: ", np.allclose(P@M, L@U))


 M = 

 [[ 1.  2. -1.  0.]
 [ 2.  4. -2. -1.]
 [-3. -5.  6.  1.]
 [-1.  2.  8. -2.]] 

 P = 

 [[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]] 

 L = 

 [[ 1.  0.  0.  0.]
 [-3.  1.  0.  0.]
 [-1.  4.  1.  0.]
 [ 2.  0. -0.  1.]] 

 U = 

 [[ 1.  2. -1.  0.]
 [ 0.  1.  3.  1.]
 [ 0.  0. -5. -6.]
 [ 0.  0.  0. -1.]]

 PM =?= LU:  True


## Solutions to Systems of Linear Equations

In [7]:
# Solving a System of Linear Equations using Gaussian Elimination 
# with Back Substitution

def solveLinearSystemGaussian(M, b):
    """
    M = n x n regular matrix
    b = n x 1 vector of constant terms
    """
    n = np.shape(M)[0]
    Mb = np.hstack((M, b))
    Uc = rowEchelonForm_NoType1(Mb)

    return backSubstitution(Uc[:, : n], Uc[:, -1])

In [8]:
# Solving a System of Linear Equations via LU-Factorization

def solveLinearSystemLU(L, U, b):
    """
    L = n x n lower triangular matrix with non-zero diagonal entries
    U = n x n upper triangular matrix with non-zero diagonal entries
    b = n x 1 vector of constant terms
    """
    y = forwardSubstitution(L, b)
    x = backSubstitution(U, y)

    return x

# Test Data

A = np.array([[-1, 0, 3], [4, 5, 6], [7, 8, 9]], dtype = 'float32')
L, U = LUFactorization(A)
b = np.array(range(3))

print("A = \n\n", A, "\n\n det(A) = ", np.linalg.det(A).round(2), "\n \n x =", solveLinearSystemLU(L, U, b))

A = 

 [[-1.  0.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]] 

 det(A) =  -6.0 
 
 x = [ 1.00000089 -1.00000107  0.33333363]


In [9]:
# LDL^T Factorization

# Test Data 1 (Numerical)
M = np.array([[1, 2, 1], [2, 6, 1], [1, 1, 4]], dtype = "float32")
L, U = LUFactorization(M)
Lt = np.transpose(L)
D = np.diag(np.diag(U))

print("\n L = \n\n", L, "\n\n D = \n\n", D, "\n\n L^T = \n\n", Lt)
print("\n M =?= LDL^T: ", np.array_equal(M, L@D@Lt))

# Test Data 2 (Symbolic)

import sympy as sp
from sympy.abc import a, b, c

M = sp.Matrix([[a, b], [b, c]])
L = sp.Matrix([[1, 0], [b/a, 1]])
U = sp.Matrix([[a, b], [0, (a*c - b**2)/a]])
D = sp.Matrix([[a, 0], [0, (a*c - b**2)/a]])
V = sp.Matrix([[1, b/a], [0, 1]])

display("M = ", M, "L = ", L, "U = ", U, "D = ", D, "V = ", V)

LU = sp.expand(L*U)
LDV = sp.expand(L*D*V)
LDLt = sp.expand(L*D*sp.transpose(L))

print(M == LU)
print(M == LDV)
print(M == LDLt)


 L = 

 [[ 1.   0.   0. ]
 [ 2.   1.   0. ]
 [ 1.  -0.5  1. ]] 

 D = 

 [[1.  0.  0. ]
 [0.  2.  0. ]
 [0.  0.  2.5]] 

 L^T = 

 [[ 1.   2.   1. ]
 [ 0.   1.  -0.5]
 [ 0.   0.   1. ]]

 M =?= LDL^T:  True


'M = '

Matrix([
[a, b],
[b, c]])

'L = '

Matrix([
[  1, 0],
[b/a, 1]])

'U = '

Matrix([
[a,              b],
[0, (a*c - b**2)/a]])

'D = '

Matrix([
[a,              0],
[0, (a*c - b**2)/a]])

'V = '

Matrix([
[1, b/a],
[0,   1]])

True
True
True
