### Programming Task No. 1
### Name: Jeremy Marcus Tan
### ID No: 204947

In [3]:
import numpy as np

In [9]:
M = np.matrix([[1,2,3], [2,3,4], [5,3,2]])
M.shape[0]


3

In [115]:
def permutedLUFactorizationWithPartialPivoting(M):
    # M is a n x n nonsingular matrix
    n = M.shape[0]
    I = np.identity(n)
    P = np.identity(n)
    U = M.copy()
    L = np.identity(n)
    for j in range(n-1): # Column Index
        # Find the row z >= j with the largest absolute value in column j
        z = np.argmax(np.abs(U[j:, j])) + j
        if j != z:
            Pcj = np.copy(P[j])
            Pcz = np.copy(P[z])
            P[j] = Pcz
            P[z] = Pcj
            Ucj = np.copy(U[j])
            Ucz = np.copy(U[z])
            U[j] = Ucz                   
            U[z] = Ucj
            Lcj = np.copy(L[j])
            Lcz = np.copy(L[z])
            for i in range(j): 
                #interchange values before the jth column 
                L[j, i] = Lcz[i]
                L[z, i] = Lcj[i]
            z = j
        if j == z:
            for i in range(j + 1, n): # i is row index
                cji = U[i, j]/U[j, j]
                U[i] = -cji*U[j] + U[i]
                L[i, j] = cji
    return [P, L, U]
            
        
    

In [116]:
M = np.random.rand(10, 10)
P,L,U = permutedLUFactorizationWithPartialPivoting(M)
print(P)
print(L)
print(U)
print(np.mean(np.abs(P@M - L@U)))


[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
[[ 1.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.98246647  1.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.88746036 -0.20217308  1.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.63420692 -0.23842375  0.53811903  1.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.1240461  -0.8447243   0.70981594 -0.22652804  1.          0.
   0.          0.          0.          0.        ]
 [ 0.74517522  0.21047281 -0.1321937  -0.13768818  0.89399122  1.
   0.          0. 

In [110]:
M = np.matrix([[-2,2,-1], [6,-6,7], [3,-8, 4]])
r,L,U = permutedLUFactorizationWithPartialPivoting(M)
print(r)
print(L)
print(U)


[1 2 0]
[[-0.33333333 -0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.5         0.          1.        ]]
[[-2  0  1]
 [ 6 -6  7]
 [ 3 -5  0]]


In [111]:
L@U

matrix([[ 0.66666667,  0.        , -0.33333333],
        [ 6.        , -6.        ,  7.        ],
        [ 2.        , -5.        ,  0.5       ]])

In [336]:
def permutedLUFactorizationWithPartialPivoting(M):
    # M is a n x n nonsingular matrix
    n = M.shape[0]
    L = np.zeros([n,n])
    r = np.arange(n)
    U = M.copy()

    
    for j in range(n): # Column Index
        max_val = 0
        previous_val = r[j]
        for i in range(j, n):
            current_val = abs(U[r[i],j])
            if current_val >= max_val:
                max_val = current_val
                z = i
        r[j] = z
        r[z] = previous_val
        print(f'Z: {z}')
        print(f'j: {j}')
        print(r)

        # Set diagonal element as 1
        L[r[j],j] = 1

        
        # Elimination step
        for i in range(j + 1, n):
            # Compute multiplier
            l_ij = U[r[i],j] / U[r[j],j]
            
            # Store multiplier in L matrix
            L[r[i], j] = l_ij
            
            # Perform row operations
            U[r[i]] -= l_ij * U[r[j]]



    print(U)
    U_final = np.identity(n)
    for i in range(n):
        U_final[i] = U[r[i]]

    L_final = np.identity(n)
    for i in range(n):
        L_final[i] = L[r[i]]

    P = np.identity(n)
    P_final = np.identity(n)
    for i in range(n):
        P_final[i] = P[r[i]]

    

    return P_final, L_final, U_final, r
    
        
        
    

In [17]:
def permutedLUFactorizationWithPartialPivoting(M):
    """
    This function performes permuted LU factorization with partial pivoting on a square nonsingular matrix.
    This algorithm computes P, L, and U matrices such that P*M = L*U.
    
    Input:
        M: n x n nonsingular matrix
        
    Outputs:
        P_final: n x n permutation matrix
        L_final: n x n unit lower triangular matrix
        U_final: n x n upper triangular matrix
        Po: Final pointer array/permutation vector for the row indices
    """
    # Get the dimension of the input matrix M
    n = M.shape[0]
    
    # Initialize L matrix as a matrix of zeros
    L = np.zeros([n, n])
    
    # Initialize pointer array for the row indices [0, 1, 2, ..., n-1]
    Po = np.arange(n)
    
    # Create a copy of M to avoid editing M directly
    U = M.copy()
    
    # Main Loop through all the columns j in M
    for j in range(n):
        # Partial Pivoting Step 
        # Find the row with largest absolute value in column j (from rows j to n-1)
        z = np.argmax(np.abs(U[Po[j:], j])) + j

        # Swap the indices in the pointer array
        index_1 = Po[j]  
        index_2 = Po[z]

        Po[z] = index_1
        Po[j] = index_2
         
        # Set diagonal element of L to 1 since L is a unit lower triangular matrix
        L[Po[j], j] = 1
        
        # Gaussian Elimination through all rows below the current pivot
        for i in range(j + 1, n):
            # Compute the multiplier 
            l_ij = U[Po[i], j] / U[Po[j], j]
            
            # Store the multiplier in the L matrix 
            L[Po[i], j] = l_ij
            
            # Perform type III elementary row operation to zero out the rows below the pivot
            U[Po[i]] -= l_ij * U[Po[j]]
    
    # Final Matrix Construction: we use the pointer array Po to rearrange the rows 
    U_final = U[Po]
    L_final = L[Po]
    P = np.identity(n)
    P_final = P[Po]
    
    return P_final, L_final, U_final, Po

In [18]:
M = np.matrix([[-2,2,-1], [6,-6,7], [3,-8,4]], dtype = float)
P,L,U,R = permutedLUFactorizationWithPartialPivoting(M)

print(P)
print(L)
print(U)
print(R)
print("\n PM =?= LU: ", np.allclose(P@M, L@U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.          0.          0.        ]
 [ 0.5         1.          0.        ]
 [-0.33333333 -0.          1.        ]]
[[ 6.         -6.          7.        ]
 [ 0.         -5.          0.5       ]
 [ 0.          0.          1.33333333]]
[1 2 0]

 PM =?= LU:  True


In [11]:
M = np.matrix([[-2,2,-1,5,3], [6,-6,7,8,9], [3,-8,4,2,5], [5,-3,2,5,3], [2,-5,3,2,1]], dtype = float)
P,L,U,R = permutedLUFactorizationWithPartialPivoting(M)

print(P)
print(L)
print(U)
print(R)
print("\n PM =?= LU: ", np.allclose(P@M, L@U))

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1.          0.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.          0.        ]
 [ 0.83333333 -0.4         1.          0.          0.        ]
 [-0.33333333 -0.         -0.36697248  1.          0.        ]
 [ 0.33333333  0.6        -0.10091743  0.04206242  1.        ]]
[[ 6.         -6.          7.          8.          9.        ]
 [ 0.         -5.          0.5        -2.          0.5       ]
 [ 0.          0.         -3.63333333 -2.46666667 -4.3       ]
 [ 0.          0.          0.          6.76146789  4.42201835]
 [ 0.          0.          0.          0.         -2.91994573]]
[1 2 3 0 4]

 PM =?= LU:  True


In [14]:

M = np.random.rand(10, 10)
M
P,L,U,R = permutedLUFactorizationWithPartialPivoting(M)

print("\n PM =?= LU: ", np.allclose(P@M, L@U))


 PM =?= LU:  True


In [45]:
# Permuted LU Factorization

def permutedLUFactorization(M):
    """
    M = n x n matrix non-singular matrix
    """
    n = np.shape(M)[0]
    I = np.identity(n)
    P = np.identity(n)
    U = M.copy() # To avoid changing the original matrix
    L = np.identity(n)

    for i in range(n - 1): # column index
        if U[i, i] == 0: # Check if the pivot is zero
            for j in range(i + 1, n): # find the row index that is nonzero
                if U[j, i] != 0:
                    Pci = np.copy(P[i])
                    Pcj = np.copy(P[j])
                    P[i] = Pcj
                    P[j] = Pci
                    Uci = np.copy(U[i])
                    Ucj = np.copy(U[j])
                    U[i] = Ucj                   
                    U[j] = Uci
                    Lci = np.copy(L[i])
                    Lcj = np.copy(L[j])
                    for k in range(i): 
                        #interchange values before the ith column as well
                        L[i, k] = Lcj[k]
                        L[j, k] = Lci[k]
                    break
        for j in range(i + 1, n): # Same as converting to upper triangular matrix
            cij = U[j, i]/U[i, i]
            U[j] = -cij*U[i] + U[j]
            L[j, i] = cij      
    
    return [P, L, U]

# Test Data

M = np.array([[1, 2, -1, 0], [2, 4, -2, -1], [-3, -5, 6, 1], [-1, 2, 8, -2]], dtype=float)    
P, L, U = permutedLUFactorization(M)

print("\n M = \n\n", M, "\n\n P = \n\n", P, "\n\n L = \n\n", L, "\n\n U = \n\n", U)
print("\n PM =?= LU: ", np.allclose(P@M, L@U))


 M = 

 [[ 1.  2. -1.  0.]
 [ 2.  4. -2. -1.]
 [-3. -5.  6.  1.]
 [-1.  2.  8. -2.]] 

 P = 

 [[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]] 

 L = 

 [[ 1.  0.  0.  0.]
 [-3.  1.  0.  0.]
 [-1.  4.  1.  0.]
 [ 2.  0. -0.  1.]] 

 U = 

 [[ 1.  2. -1.  0.]
 [ 0.  1.  3.  1.]
 [ 0.  0. -5. -6.]
 [ 0.  0.  0. -1.]]

 PM =?= LU:  True
