### Programming Task No. 1
### Name: Jeremy Marcus Tan
### ID No: 204947

In [4]:
import numpy as np

In [5]:
def permutedLUFactorizationWithPartialPivoting(M):
    """
    This function performes permuted LU factorization with partial pivoting on a square nonsingular matrix.
    This algorithm computes P, L, and U matrices such that P*M = L*U.
    
    Input:
        M: n x n nonsingular matrix
        
    Outputs:
        P_final: n x n permutation matrix
        L_final: n x n unit lower triangular matrix
        U_final: n x n upper triangular matrix
        Po: Final pointer array/permutation vector for the row indices
    """
    # Get the dimension of the input matrix M
    n = M.shape[0]
    
    # Initialize L matrix as a matrix of zeros
    L = np.zeros([n, n])
    
    # Initialize pointer array for the row indices [0, 1, 2, ..., n-1]
    Po = np.arange(n)
    
    # Create a copy of M to avoid editing M directly
    U = M.copy()
    
    # Main Loop through all the columns j in M
    for j in range(n):
        # Partial Pivoting Step 
        # Find the row with largest absolute value in column j (from rows j to n-1)
        z = np.argmax(np.abs(U[Po[j:], j])) + j

        # Swap the indices in the pointer array
        index_1 = Po[j]  
        index_2 = Po[z]

        Po[z] = index_1
        Po[j] = index_2
         
        # Set diagonal element of L to 1 since L is a unit lower triangular matrix
        L[Po[j], j] = 1
        
        # Gaussian Elimination through all rows below the current pivot
        for i in range(j + 1, n):
            # Compute the multiplier 
            l_ij = U[Po[i], j] / U[Po[j], j]
            
            # Store the multiplier in the L matrix 
            L[Po[i], j] = l_ij
            
            # Perform type III elementary row operation to zero out the rows below the pivot
            U[Po[i]] -= l_ij * U[Po[j]]
    
    # Final Matrix Construction: we use the pointer array Po to rearrange the rows 
    U_final = U[Po]
    L_final = L[Po]
    P = np.identity(n)
    P_final = P[Po]
    
    return P_final, L_final, U_final, Po

In [50]:
# Test the function using a 10x10 random matrix with entries from a standard normal distribution

M = np.random.randn(10, 10)
P,L,U,R = permutedLUFactorizationWithPartialPivoting(M)
print("\n PM =?= LU: ", np.allclose(P@M, L@U))
print(f'The average of the absolute values of the entries of PM - LU is {np.mean(np.abs(P@M - L@U))}.')
print("\n M = \n\n", M, "\n\n P = \n\n", P, "\n\n L = \n\n", L, "\n\n U = \n\n", U)



 PM =?= LU:  True
The average of the absolute values of the entries of PM - LU is 4.765285388508289e-17.

 M = 

 [[ 0.25960487 -2.14137912  1.31261688  1.50899899 -0.14244787 -0.39060668
  -1.25221813 -0.07623913 -1.22200803 -1.91338314]
 [ 0.18708243 -0.44946918 -0.26954591 -0.05486405 -0.31148149  0.89985411
   0.69090106  0.08692799  1.10797102 -1.42564849]
 [-1.23694916 -0.55668484  0.41377447 -0.45692375 -0.71770397 -0.01241049
   1.04981319  0.13431807  0.81518375  0.25617676]
 [-0.09348221 -0.44348416  0.70028099  0.41886254 -0.11296793  0.30377591
  -0.33536601 -1.10151857  0.7487362  -0.64571132]
 [-0.4398347   1.39841827  3.25842245 -0.26364854  0.77558102  0.80706405
  -0.13357064  0.62426342  0.17340801  0.55531234]
 [-1.68860613  0.95597967  0.56906929 -0.35863656 -1.16307201 -0.00897433
   0.03993048 -0.57346553 -0.138287    0.17421796]
 [ 0.25525215  0.21405161  0.62208466 -0.19427089 -0.53626656 -0.66279543
   0.04422626  1.1251818   0.22832313 -0.87381506]
 [ 0.17331

In [10]:
M = np.matrix([[-2,2,-1], [6,-6,7], [3,-8,4]], dtype = float)
P,L,U,R = permutedLUFactorizationWithPartialPivoting(M)

print("\n M = \n\n", M, "\n\n P = \n\n", P, "\n\n L = \n\n", L, "\n\n U = \n\n", U)
print("\n PM =?= LU: ", np.allclose(P@M, L@U))
print(f'The average of the absolute values of the entries of PM - LU is {np.mean(np.abs(P@M - L@U))}.')


 M = 

 [[-2.  2. -1.]
 [ 6. -6.  7.]
 [ 3. -8.  4.]] 

 P = 

 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

 L = 

 [[ 1.          0.          0.        ]
 [ 0.5         1.          0.        ]
 [-0.33333333 -0.          1.        ]] 

 U = 

 [[ 6.         -6.          7.        ]
 [ 0.         -5.          0.5       ]
 [ 0.          0.          1.33333333]]

 PM =?= LU:  True
The average of the absolute values of the entries of PM - LU is 0.0.


In [7]:
M = np.matrix([[-2,2,-1,5,3], [6,-6,7,8,9], [3,-8,4,2,5], [5,-3,2,5,3], [2,-5,3,2,1]], dtype = float)
P,L,U,R = permutedLUFactorizationWithPartialPivoting(M)

print(P)
print(L)
print(U)
print(R)
print("\n PM =?= LU: ", np.allclose(P@M, L@U))
print

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1.          0.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.          0.        ]
 [ 0.83333333 -0.4         1.          0.          0.        ]
 [-0.33333333 -0.         -0.36697248  1.          0.        ]
 [ 0.33333333  0.6        -0.10091743  0.04206242  1.        ]]
[[ 6.         -6.          7.          8.          9.        ]
 [ 0.         -5.          0.5        -2.          0.5       ]
 [ 0.          0.         -3.63333333 -2.46666667 -4.3       ]
 [ 0.          0.          0.          6.76146789  4.42201835]
 [ 0.          0.          0.          0.         -2.91994573]]
[1 2 3 0 4]

 PM =?= LU:  True
