# Programming Task No. 2
Luis Gabriel K. Villadarez

205377


In [4]:
import numpy as np

# Utility Function 

def basis (R):
    # Step 1: Extract the diagonal of R
    diagonal_entries = np.diag(R)
    
    # Step 2: Take the absolute value of each diagonal entry
    absolute_diagonal = np.abs(diagonal_entries)
    
    # Step 3: Compare each entry to a small threshold to determine independence
    independence_flags = absolute_diagonal > 1e-10
    
    # Step 4: Get the indices where the entry is considered independent
    independent_cols = np.where(independence_flags)[0]

    return independent_cols

    
# Main Function
def ModifiedGramSchmidt(M):
    """
    Algorithm 2: Modified Gram-Schmidt
    M = m x n matrix
    Qo = m x n orthonormal matrix
    Q = m x k matrix where k = rank(M) is the number of linearly independent columns of M
    Input: M
    Returns: Q
    """
    m, n = M.shape
    V = M.copy() # copy of original matrix M
    Qo = np.zeros((m, n))  # Initialize temporary matrix Qo to store orthonormalized vectors
    R = np.zeros((n, n))  # Initialize square upper triangular matrix R

    for j in range(n):
        for i in range(j):
            R[i, j] = np.dot(V[:, j], Qo[:, i]) # r_ij from pseudocode

        # r_jj from pseudocode
        # Define rjj_squared first before determining rjj to impose restriction for rjj_squared
        rjj_squared = np.dot(V[:, j], V[:, j]) - sum(R[k, j]**2 for k in range(j))
        R[j, j] = np.sqrt(rjj_squared) if rjj_squared > 1e-10 else 0.0 # to avoid very small negative number due to floating-point rounding error that will cause sqrt to be undefined

        if R[j, j] == 0: # to avoid division by zero
            Qo[:, j] = 0.0  # this column is linearly dependent and will be filtered out by utility function
        else:
            Qo[:, j] = (V[:, j] - sum(R[k, j] * Qo[:, k] for k in range(j))) / R[j, j] # u_j from pseudocode

    # Keep only independent columns (columns that correspond to a basis)
    independent_cols = basis(R) # final orthonormal basis must exclude those zero columns (not linearly ind) as they do not contribute to the column space
    Q = Qo[:, independent_cols]
    return Q

    
# Test Data

# Test Data
m = 5
n = 8

for i in range(5):
  M = np.random.rand(m, n)

  Q = ModifiedGramSchmidt(M)
  QT = np.transpose(Q)
  I = np.eye(M.shape[0])

  print("="*60)
  print(f'Test {i+1}\n')
  print('M=\n', M)
  print('\nQ=\n', Q)
  for j in range(Q.shape[1]):
        for i in range(j):
            print(f'The dot product between columns {i} and {j} is {np.dot(Q[:, i], Q[:, j])}')
        for j in range(Q.shape[1]):
            print(f'The norm of column {j} is {np.linalg.norm(Q[:, j])}')
  # Check if QQ^T = I
  print(f"\nQQ^T =?= I: {np.allclose(Q @ QT, I)}")

  # Calculate the average absolute error
  print(f"Average Absolute Error (QQ^T - I): {np.mean(np.abs(Q @ QT -I))}")

Test 1

M=
 [[0.82508242 0.43849586 0.62026817 0.33409837 0.39814127 0.01061832
  0.63777414 0.26449083]
 [0.78701962 0.66900592 0.03409055 0.05661513 0.2810864  0.00267732
  0.33354939 0.06894246]
 [0.72546115 0.12677652 0.91359351 0.62304106 0.8708317  0.65667399
  0.80703028 0.20774921]
 [0.57685258 0.83113361 0.18574649 0.59882728 0.46956786 0.83745786
  0.53490166 0.88242092]
 [0.91504103 0.98806894 0.02912447 0.4307685  0.45062161 0.05453305
  0.30414119 0.84032011]]

Q=
 [[ 0.47663858 -0.31375338  0.08861598 -0.6719651  -0.46366431]
 [ 0.45465024  0.07113376 -0.59967851 -0.21620425  0.61795999]
 [ 0.41908877 -0.65815516  0.32090208  0.47727563  0.24581744]
 [ 0.33323968  0.55556797  0.6835998  -0.14283638  0.30427722]
 [ 0.52860642  0.39328719 -0.24949159  0.50351204 -0.50013   ]]
The norm of column 0 is 1.0
The norm of column 1 is 0.9999999999999999
The norm of column 2 is 1.0000000000000018
The norm of column 3 is 1.0000000000000084
The norm of column 4 is 1.0000000000000042
T