# Programming Task No. 2
- **Benjamin Louis L. Ang**
- **200302**

## Utility Function

In [ ]:
import numpy as np

def basis_columns(M, tol=1e-10):
    """
    Determine which columns of M form a basis for im(M).
    We do a simple greedy Gram–Schmidt on columns of M,
    and whenever the new vector has norm > tol after removing
    projections onto previous, we keep it.
    Returns the list of column indices.
    """
    m, n = M.shape
    Q_temp = []         # will hold the orthonormal vectors
    basis_idxs = []     # will hold the indices of original columns
    for j in range(n):
        v = M[:, j].copy()
        # remove projections onto each previously accepted direction
        for q in Q_temp:
            v -= np.dot(q, v) * q
        if np.linalg.norm(v) > tol:
            q_new = v / np.linalg.norm(v)
            Q_temp.append(q_new)
            basis_idxs.append(j)
    return basis_idxs

## Main Function

In [ ]:
def ModifiedGramSchmidt(M, tol=1e-10):
    """
    Implements the Modified Gram–Schmidt orthonormalization.
    Input:  M (m×n)
    Output: Q (m×r), where r = rank(M), and columns of Q are orthonormal
    """
    m, n = M.shape
    # first pick the independent columns
    pivots = basis_columns(M, tol)
    Q_list = []
    for j in pivots:
        v = M[:, j].copy()
        # remove projections onto already-built Q_list
        for q in Q_list:
            v -= np.dot(q, v) * q
        norm_v = np.linalg.norm(v)
        if norm_v > tol:
            Q_list.append(v / norm_v)
        # if norm_v <= tol, that column was essentially dependent, skip
    # stack into a matrix
    if len(Q_list) > 0:
        Q = np.column_stack(Q_list)
    else:
        Q = np.zeros((m, 0))
    return Q


In [2]:
np.random.seed(0)
for test_id in range(1, 6):
    M = np.random.randn(5, 8)
    Q = ModifiedGramSchmidt(M)
    print(f"--- Test {test_id} ---")
    print("M shape:", M.shape, "→ Q shape:", Q.shape)
    # Check orthonormality: QᵀQ should be identity of size rank
    QTQ = Q.T @ Q
    print("QᵀQ =\n", np.round(QTQ, 6))
    print()

--- Test 1 ---
M shape: (5, 8) → Q shape: (5, 5)
QᵀQ =
 [[ 1.  0. -0.  0.  0.]
 [ 0.  1.  0. -0.  0.]
 [-0.  0.  1. -0.  0.]
 [ 0. -0. -0.  1. -0.]
 [ 0.  0.  0. -0.  1.]]

--- Test 2 ---
M shape: (5, 8) → Q shape: (5, 5)
QᵀQ =
 [[ 1.  0.  0. -0. -0.]
 [ 0.  1. -0.  0.  0.]
 [ 0. -0.  1. -0.  0.]
 [-0.  0. -0.  1. -0.]
 [-0.  0.  0. -0.  1.]]

--- Test 3 ---
M shape: (5, 8) → Q shape: (5, 5)
QᵀQ =
 [[ 1.  0. -0. -0.  0.]
 [ 0.  1.  0. -0. -0.]
 [-0.  0.  1.  0.  0.]
 [-0. -0.  0.  1. -0.]
 [ 0. -0.  0. -0.  1.]]

--- Test 4 ---
M shape: (5, 8) → Q shape: (5, 5)
QᵀQ =
 [[ 1. -0.  0. -0.  0.]
 [-0.  1. -0.  0. -0.]
 [ 0. -0.  1. -0.  0.]
 [-0.  0. -0.  1.  0.]
 [ 0. -0.  0.  0.  1.]]

--- Test 5 ---
M shape: (5, 8) → Q shape: (5, 5)
QᵀQ =
 [[ 1.  0. -0.  0.  0.]
 [ 0.  1.  0.  0. -0.]
 [-0.  0.  1. -0.  0.]
 [ 0.  0. -0.  1. -0.]
 [ 0. -0.  0. -0.  1.]]

